services:
  - type: web
    name: agrohub
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn agrohub.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: agrohub-db
          property: connectionString

databases:
  - name: agrohub-db
    databaseName: agrohub
    user: agrohub
