# Generated by Django 5.0.6 on 2026-05-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fas fa-star', max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('cta_text', models.CharField(default='Explore Products', max_length=100)),
                ('cta_link', models.CharField(default='/products/', max_length=200)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('background_overlay_color', models.CharField(default='rgba(0,0,0,0.55)', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='East Africa AgroHub Export Ltd', max_length=200)),
                ('tagline', models.CharField(default='From East Africa to Global Markets', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_title', models.CharField(default='About Us', max_length=200)),
                ('about_text', models.TextField(default='East Africa AgroHub Export Ltd is a Tanzania-based agricultural export company...')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('vision', models.TextField(default="To become one of Africa's leading and most trusted agricultural export companies connecting local producers to international markets.")),
                ('mission', models.TextField(default='To deliver premium agricultural products with integrity, efficiency, and international quality standards while empowering local agricultural value chains.')),
                ('phone', models.CharField(default='+255 685 047 428', max_length=50)),
                ('email', models.EmailField(default='export@eastafricaagrohub.co.tz', max_length=254)),
                ('location', models.CharField(default='Dar es Salaam, Tanzania', max_length=300)),
                ('google_maps_embed', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(default='East Africa AgroHub Export Ltd - Premium agricultural exports from Tanzania to global markets.', max_length=300)),
                ('meta_keywords', models.CharField(default='agricultural export, Tanzania, East Africa, grains, horticulture, meat, seafood', max_length=500)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok')], max_length=50)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fas fa-chart-line', max_length=100)),
                ('number', models.CharField(help_text='e.g. 500+', max_length=50)),
                ('label', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fas fa-check-circle', help_text='FontAwesome icon class e.g. fas fa-seedling', max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Item',
                'verbose_name_plural': 'Why Choose Us Items',
                'ordering': ['order'],
            },
        ),
    ]
